services:

  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    command: npm start
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./server:/usr/app
    depends_on:
      - database
    environment:
      PORT: ${SERVER_PORT}
      DATABASE_URL: mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database/${DATABASE_NAME}
  
  database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
